config/routes.rb
Rails.application.routes.draw do
   resources :comments
  root 'comments#index'
  require 'sidekiq/web'
	mount Sidekiq::Web => '/sidekiq'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	def self.lists
		ids = find_by_sql("SELECT array_to_string(array_agg(id order by id desc), ',') as id, count(*) as cnt, 
            to_timestamp(floor((extract('epoch' from created_at) / 300 )) * 300) 
            as interval_alias
            FROM comments GROUP BY interval_alias,ip_address  order by 1,2").map(&:id)    
		where(:id =>ids).order(:id => :desc)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.lists
    @comment = Comment.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @comment = Comment.new(comment_params.merge(:ip_address => request.remote_ip))
    respond_to do |format|
      if @comment.save
        @comments = Comment.lists
        format.js
      else
        format.html { render :new }
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_index.html.erb
<div id='comment-container' class='container row'>
  <% @comments.each do |comment| %>
    <div id='comments-list' class='col-md-8 justify-content-md-center'>
      <span>
        <b>Comment from IP: </b>
      <span> 
      	<%= comment.ip_address%> <b>at</b> <%= comment.created_at.to_s(:db)%>
      </span>
      </span>
    </div >
    <div class='col-xs-12 col-md-8 '>
    	<ul>
    		<%= sanitize(comment.notes, tags: %w(b i)).html_safe %>
    	</ul> 
    </div>
    <br/>
  <% end %>
</div>

app/views/comments/_new.html.erb
<%= form_for @comment,  :url => comments_path(@comment), :remote => true do |f| %>


<%= f.text_area :notes,{:class=>"form-control" ,:rows=>"4" ,:placeholder=>"Exception Log comments."} %>

<%= submit_tag 'Post', :class => 'pull-right margin-top btn btn-default' %>
<% end %>

app/views/comments/create.js.erb
container = $('#sample	');
container.html( "<%= j render( :partial => 'comments/index' ) %>" );

$('#comment_notes').val('');

app/views/comments/index.html.erb
<%- model_class = Comment -%>

<div class="row"  >
  <div class="col-md-6 col-md-offset-3"  style="border:1px solid ">

		<h3>Add new comment</h3>
		<%= render 'new' %>

		<h3>Comments</h3>
		<hr>
		<div id='sample'>
		<%= render 'index' %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Posts" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Posts</a>
        
      </div>
    </div>

    <div class="container">
      <div class="row">
        
          <%= bootstrap_flash %>
          <%= yield %>
        
       

      <footer>
        <!-- <p>&copy; Company 2018</p> -->
      </footer>

    </div> <!-- /container -->

  </body>
</html>